--- 
name: phone_spec
bbver: 5.0
sdk: /Users/crystax/work/rhomobile/rhodes
#applog: rholog.txt
version: 1.0.0
vendor: rhomobile
sdkversion: 1.4
wmsdk: "Windows Mobile 6 Professional SDK (ARMV4I)"
iphone: 
  sdk: iphonesimulator4.2
  entitlements: ""
  codesignidentity: ""
  configuration: Release
  extensions: ["barcode"]
  
android:
  apikey: "0tLch9tZSX1G7PQRWwmqvINECUGtJ8ReArpPJxw"
  mapping: enabled
  capabilities:
    - network_state
    
  extensions: ["barcode"]
  
wm:
  extensions: ["barcode"]
  
bb:
  extensions: ["barcode"]
      
capabilities:
  - pim
  - push
  - calendar
     
extensions: ["json", "rhoxml", "rhospec", "crypt"]  

